### create Report
POST http://localhost:3000/reports
content-type: application/json

{
   "price": 400000,
   "make": "toyota",
   "model": "corolla",
   "year": 1980,
   "mileage":10000,
   "lng":0,
   "lat":0
}

### Approve an existing Report
PATCH http://localhost:3000/reports/1
content-type: application/json

{
   "approved": true
}

### Get An Estimate for an existing Vehicle
GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=20000&year=1980