### create Report
POST http://localhost:3000/reports
content-type: application/json

{
   "price": 20000,
   "make": "ford",
   "model": "mustang",
   "year": 1982,
   "mileage":50000,
   "lng":45,
   "lat":45
}

### Approve an existing Report
PATCH http://localhost:3000/reports/13
content-type: application/json

{
   "approved": true
}

### Get An Estimate for an existing Vehicle
GET http://localhost:3000/reports?make=ford&model=mustang&lng=45&lat=45&mileage=50000&year=1981