### Create a new User
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "test@mail.com",
    "password": "test"
}

### Find a particular User with a given id
GET http://localhost:3000/auth/2


### Find all Users with a given email
GET http://localhost:3000/auth?email=test@mail.com

### Delete a User with a given id
DELETE  http://localhost:3000/auth/1

### Update a User with a given id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "talaat@gmail.com",
    "password": "test"
}